services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: full_food_app
    restart: unless-stopped
    env_file:
      - .env
    environment:
      PORT: 3000
      DATABASE_URL: file:../data/dev.db
    ports:
      - '3000:3000'
    volumes:
      - app_data:/app/data

volumes:
  app_data:
